### PR TITLE
Inventory Information

### PR DESCRIPTION
**Pull request by monicasinghrana**

### CODE REVIEW

**Comment by monicasinghrana** [comment]
Application to upload and view inventory information

**Comment by nrigroup** [comment]
Thank you for your submission.

None of us have used codeigniter before so we need some instruction how to get your code up and running so we can try it out.

Please send us directions so that we can better evaluate your work.

**Comment by monicasinghrana** [comment]
Thanks for reviewing my code. I thought i can use any MVC framework that is why i used codeignitor.
Installing and setting all the route files, config files and database files  might take lot of you time. To avoid all that i have changed my code. No framework needed. 

 Now there are only three files in New_files.zip. 

- Load all the files in the same location. 

- Change database credentials and table name in main_db.php.

-  Create 'upload' folder in teh smae loctaion where files are. Make sure 'upload' folder has the right permissions( Apache writable') otherwise upload will fail.

- Execute upload_view.php for file upload.  

- Execute spending_view.php for view total spending.

Apart from this project here is an example of some of my work i have done using bootstrap:
http://www.globalstar.com/whatmatters
http://www.globalstar.com/prepared

Let me know if you have any questions

Thanks
Monica Rana

**Comment by nrigroup** [comment]
Hi Monica.

Codeigniter is fine.  Laravel would be our preference as that's what we use, but mainly we want to see an understanding of MVC concepts.

With that in mind, we would actually prefer if you could upload a solution that includes all the framework code, including route, config files etc.  As I said, the main thing is we want to see that your able to use all the MVC concepts.

If you could give us instructions to install it to please.  We may not have time to install it ourselves, but in case we do.

Thanks,

Scott

**Comment by monicasinghrana** [comment]
Hi Scott,

I have uploaded new set of files folder name project_jan19. I have tried to add all the instruction to execute this project once you have Codeigniter installed. I have been using Codeigniter from past five years therefore adapting a new MVC will never be an issue.
Let me know if you have any questions.

Thanks
Monica Rana

**Comment by nrigroup** [comment]
Hi Monica.

I was hoping you could upload the whole codeigniter application.  I shouldn't need to install it myself and then copy your folders into the correct place.  Ideally I would just need to change the database credentials and do my web server config and little else.  Would you be able to upload it this way?

Scott

**Comment by monicasinghrana** [comment]
Hi Scott,
I don't have my own server where i can install Codeigniter and make all change to make it work. 
I have development  work server but i don't want to use that for my personal use.
I hope from my code you get an idea of my coding skills and MVC framework knowledge.

Thanks
Monica Rana

**Comment by nrigroup** [comment]
Hi Monica.  I understand, we will review your code and pass our assessment onto our HR manager for further communication.

Scott

**Pull request closed without merging**
