### PR TITLE
Solution to the Challenge

### PR DESCRIPTION
**Pull request by juliusmayiga**
I am Julius Mayiga
I have done my solution using CodeIgniter

### CODE REVIEW

**Comment by juliusmayiga** [comment]
I have just realised that all my commits that I have pushed using github  desktop are tagged as cacoder which is my former user name of github though I changed to techyjulius but I GitHub Desktop is still I guess holding it.

**Comment by nrigroup** [comment]
Thank you for your submission.  
I have reviewed your submission and had some questions.
1. In `controllers/Inventory.php` in functions `expenses_html` and `expense_per_month_table` and `expense_per_category_table`, you have constructed html code. Can you explain why you've mixed controller logic and view logic?
2. I saw you built your own `nri.css` instead of using bootstrap or any other popular front end frameworks, which is perfectly fine, but is there a reason for that? (maybe you're not familiar with bootstrap?)
3.  Are you aware what ORM is? if you're why haven't you used it? if not, please ignore this question.

Thank you.

**Comment by juliusmayiga** [comment]
ANSWER TO QN 1
I mixed that up because of two factors, time and my style of coding. With my coding style I usually ensure that views files only echo out content and never do anything else even if its as simple as assigning variables data. Looking at the functions expenses_html, expense_per_month_table and expense_per_category_table you realize that they involve some logic to them as they build up the table markup which I didn't want to be done in the views file. Usually when am coding functions that generate views content I put them in their own library file which is just called in the controllers and then parsed to the views files but with the interest if time I didn't separate those functions to be put into their own library file.

ANSWER TO QN 2
I chose to do away with bootstrap because the design concept that I wanted to achieve was too simple and would perfectly be achieved without using it. Further more my comfort level with bootstrap is not high since I am more into back end development but with key strength in front end too.

ANSWER TO QN 3
I'am aware of ORM, but with the interest of time i didn't go into it.

Thank You

**Comment by nrigroup** [comment]
RE: **ANSWER TO QN 1**

I am a bit concerned the way you responded to Q#1
I don't know if you fully understand the concept of MVC.
The way you answered the Q#1 suggests that you are totally disregarding V part of MVC,
making it MC framework. 

Usually big projects' view file yields more than 1000 lines of html. Imagine you're putting all those html lines into controller. This would be very problematic in the long run.  

Furthermore, I believe you can actually **save time** doing a proper implementation of MVC.  

So I take this opportunity to invite you to submit another pull request implementing a proper MVC. Please take a look at this [link](http://www.codeigniter.com/user_guide/general/views.html) and this [link](http://www.codeigniter.com/user_guide/libraries/parser.html) if you're not too sure what V does in MVC.

**Comment by juliusmayiga** [comment]
I perfectly understand the concept of MVC.
However, for my case I keep the view to only displaying (echoing) content which is why I didn't put the table markup building into the views file ( i.e I couldn't put the foreach/for loop into the views file because it contained some logic in it )
Furthermore I have two pages where the tables are rendered which means if I had to transfer the code for generating tables into views I would have to duplicate the table generating code on each of the views that render those two pages.
Like I said "Usually when am coding functions that generate views content I put them in their own library file which is just called in the controllers and then parsed to the views files but with the interest if time I didn't separate those functions to be put into their own library file."

**Comment by nrigroup** [comment]
Your answers are noted.
Thank you!

**Comment by juliusmayiga** [comment]
Thanks, I will be submitting another pull request tonight that implements what you have requested for.

**Comment by juliusmayiga** [comment]
I have separated views from the controller and I have also created a library to house all the functions/methods that were not pages that I had included in the controller class.
Let me know if further changes are needed to get this right.
Thanks

**Comment by nrigroup** [comment]
Hello,

We have received your submission.
We will review it and contact you through email.

Thanks

**Comment by juliusmayiga** [comment]
Thanks

**Pull request closed without merging**
