### PR TITLE
Coding webdev-challenge

### PR DESCRIPTION
**Pull request by noldsel**

### CODE REVIEW

**Comment by noldsel** [comment]
Hi, my name is Arnold Seloterio
I have coded my solution using Yii Framework version 2

**Comment by nrigroup** [comment]
Hi, Thanks for the submission.
We have tried to spin up a fresh vm to test your code however, we failed to start it up.
Does your installation steps take consideration that we are starting from a fresh VM?  

Do we have to install composer? do we have to install yii?
What's the exact dependencies?  

We installed composer, then `composer install` inside `codes` folder. Then visited `web/index.php?r=installer`, then we presented with:
http://i.imgur.com/1uBUMoA.png  

We do not use Yii here, so please tell us the exact steps.

**Comment by noldsel** [comment]
Hi, 

There should be no extra steps needed for the installation if it is done on VM

At this point, there should be no need to install Yii at your end. All you need to do is copy the folder 'webdev-challenge' into the webserver's document root. But please make sure to  change permission to chmod 777 on the folloing folders:
-  webdev-challenge/codes/web/assets
-  webdev-challenge/codes/web/uploads

After copying the 'webdev-challenge' folder, you should be able to point your browser to:

(instructions to initialize database backend structure) http://localhost/webdev-challenge/codes/web/index.php?r=installer
(front end to accept csv file upload and input) http://localhost/webdev-challenge/codes/web/index.php?r=inventory/upload

**Comment by noldsel** [comment]
Please take note that these are the following files I have written on top of the Yii framework:
- codes/controllers/InstallerController.php
- codes/controllers/InventoryController.php
- codes/views/installer/index.php
- codes/views/_stat_per_category.php
- codes/views/_stat_per_month.php
- codes/views/upload.php
- codes/models/Categories.php
- codes/models/ContactForm.php
- codes/models/Inventory.php
- codes/models/InventoryQuery.php
- codes/models/LotCondition.php
- codes/models/TaxName.php
- codes/models/UploadForm.php

All other codes that you see in the folders are generated by the Yii framework

**Comment by nrigroup** [comment]
Hi,  

We tried it again. It does not work. error 500.
We have php 5.5.9 and apache2 with mysql.  

Maybe you can spin up an amazon instance or a vm and we can visit it there?

**Comment by noldsel** [comment]
Hi,

I have created an amazon instance and uploaded the codes.

You may access it here:

http://54.173.231.128/webdev-challenge/codes/web/index.php?r=inventory/upload

Please take note that if you upload the csv more than once, the statistics might change. This is because the 19 records from data.csv file will be added into the database every time you upload the file

Right now, there database is empty, so you should have a clean statistics the first time you upload the data.csv file

**Comment by noldsel** [comment]
Hi, 

May I know if you could access the amazon ec2 server that I have created last Friday? You can see that my codes are working with a clean interface.

**Comment by nrigroup** [comment]
Hi,

We did access the site. Thank you for putting it up online.
You can remove it if you wish to.

We will communicate further through email.
Thank you

**Pull request closed without merging**
