### PR TITLE
Scott Davis Coding Challenge Submission

### PR DESCRIPTION
**Pull request by sdavis1902**

### CODE REVIEW

**Comment by sdavis1902** [comment]
Just wanted to add, that I did not include any instructions on the webserver and domain setup.  These would vary from one installation to another, so is not generally the type of thing that is included in the instructions.  About the only thing worth mention, is that you have to point to the public folder ( this is probably obvious, but still worth a mention ).  Laravel requires little out of the ordinary setup with apache, but on my development machine, I actually prefer nginx.  In case your interested, here is my nginx configuration:

server {
    listen   80;
    server_name sd.webdevchallenge.com;
    root /var/www/html/sd/webdev-challenge/public;

```
index index.php;

location / {
    try_files $uri $uri/ /index.php?$args ;
}
location ~ \.php$ {
    try_files $uri /index.php =404;
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_index index.php;
    fastcgi_param
    SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
}
```

}

I do my development directly on my laptop running Linux Mint, but to simulate a real web domain, I add the following to /etc/hosts:
127.0.0.1       sd.webdevchallenge.com

**Comment by nrigroup** [comment]
Hi, 

Thank you for participating in the interview process.
We did review your code and the application. 
We just used `php artisan serve`, everything worked fine!

Everything looked great. Love the dropzone.js and dataTable integration.

Some questions though:
- Why haven't you defined a model for the `item` or `category`?
- Do you know how to implement testing within Laravel?
- How long did it take you to come up with this code?

Thank you.
Terry

**Comment by sdavis1902** [comment]
Hello Terry.

Thanks for the reply.  I really like it with dropzone as well, feels like a much nicer, more modern flow.  I really like using datatables.  It looks nice and has a lot of nice functionality.  I've also used datatables where it is populated via ajax calls.  A little more work that way, but for a large data set, it is great and is so much easier than trying to coble together your own pagination.  I really like these sort of js libraries since my design skills are not that good and they do a lot of the work of looking nice for me!

I do have an model for item, it's located under app/Models/Item.php.  I thought about creating another table for categories, but did not for a couple reasons.  First one is time, I didn't have time to polish a few things as much as I would have liked.  Second, since the categories are text within the csv file, using this to populate a second table is not real reliable.  A user might enter "Hardware" or "Hardware, or they might put "Plastics & Rubber" or "Plastics&Rubber".  As such, I treated categories more as an information field.  In a full application in reality, there would probably be a better way to have category specified within the csv which would allow for consistent data, in which case a separate table and model would be sensible.

No, I do not know how to implement testing within Laravel, it's not something I've had to do before.  I've heard and read about coding things a certain way to allow unit testing, but have yet to delve into it myself.

It took me about 3 hours.  A lot of what I did, I've done the same stuff, or something similar before, so I was able to borrow from other code.  I've used the admin panel within Laravel before, but it was laravel 4, not 5, so there where a few things I needed to fix.  I've used dropzone once before as well, so I was familiar with that.  I've also used league/flysystem and league/csv before.  When you find good tools, is beneficial to reuse them when it makes sense as it saves a lot of time.

**Comment by nrigroup** [comment]
Hi,

Thank you for your reply.
We will be in touch very soon!

T

**Comment by sdavis1902** [comment]
Hi Terry, thanks for the time.

I just wanted to say, I enjoyed the challenge and it has me excited to further pursue this position, as this is the sort of work I enjoy doing.  Presumably, if this is your code challenge, a lot of the work you do is liable to be similar.

One other thing I'd like to share with you.  I recently worked on a project that I needed to host on a shared server, which did not meet the Laravel requirments.  I decided to just build something from scratch using various composer packages.  Over time, it ended up evolving into a full MVC.  It was not my intent when I started, but I ended up creating my own framework!  If your interested, you can check it out here.

https://bitbucket.org/s_davis1902/kasuwa/src

**Comment by nrigroup** [comment]
Hi,

This is definitely going to be a bonus point.
Although, I'd love to see you use VPS than a shared hosting.
We will talk more when we see face to face.

Thank you!

**Comment by sdavis1902** [comment]
I'd prefer to use VPS as well, but there is a good reason I didn't in this case.  It's a personal project I've been working on slowly in my off time.  Given that, I don't want to spend any money on it.  My father in law happens to have a site on shared hosting which I manage for him and it allows for multiple domains and to point them at folders below the main web root.  So basically, I can put additional sites there for free.  It has ssh access fortunatly and I was able to use rocketeer ( http://rocketeer.autopergamene.eu/ ) for deploying to it, which was also fun to set up.

If this was a paid project for someone, I would absolutely use a VPS though.  But I do find, non ideal situations like this one are often good learning experiences as they force you to adapt and try new methods.

**Pull request closed without merging**
